### ISSUE TITLE
Error: ENOENT: no such file or directory, open workbox-v3.6.3/workbox-sw

### ISSUE THREAD

**Issue by zanjs** [lvzhenbang/webpack4.x-multi-page#1]
```
Error: ENOENT: no such file or directory, open workbox-v3.6.3/workbox-sw
```

**Comment by lvzhenbang** [comment]
Fisrt, you need to find ‘build/webpack.config.js’。

then, 
fix:
`
      // new Workbox.GenerateSW({
        //   clientsClaim: true,
        //   skipWaiting: true,
        //   importWorkboxFrom: 'local'
        // }),
        new Workbox.InjectManifest({
          // importWorkboxFrom: 'local',
          importsDirectory: path.join(__dirname, '../dist'),
          swSrc: path.resolve(__dirname, '../dist/workbox-v3.6.3/workbox-sw.js'),
          swDest: path.resolve(__dirname, '../dist/service-worker.js')
        })
`

to:
 `
       new Workbox.GenerateSW({
          clientsClaim: true,
          skipWaiting: true,
          importWorkboxFrom: 'local'
        }),
        // new Workbox.InjectManifest({
        //   // importWorkboxFrom: 'local',
        //   importsDirectory: path.join(__dirname, '../dist'),
        //   swSrc: path.resolve(__dirname, '../dist/workbox-v3.6.3/workbox-sw.js'),
        //   swDest: path.resolve(__dirname, '../dist/service-worker.js')
        // })
`
Note: If you use `Workbox.GenerateSW`, it creates a problem that the network cannot access. So the best way is to localize ' workbox-sw '. But it can only pass through ` Workbox.InjectManifest` realize.

you visit [` issue `](https://github.com/GoogleChrome/workbox/pull/1148)

**Comment by zanjs** [comment]
thanks
