### ISSUE TITLE
README 中的一些文章链接已失效

### ISSUE THREAD

**Issue by AmyFoxFN** [lvzhenbang/webpack4.x-multi-page#7]
Thanks for your time! 最近在做一些多页应用的事情，看到[你的文章](https://segmentfault.com/a/1190000017393930)写的比较好，对我很有帮助，本来想看一下整个系列，但发现链接失效了，请问哪里可以访问到这些文章吗？

**Comment by lvzhenbang** [comment]
@AmyFoxFN [文章路径](https://github.com/lvzhenbang/webpack-play/tree/master/doc/other)

**Comment by AmyFoxFN** [comment]
谢谢🙏
